default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: log_manager_app_development

test:
  <<: *default
  database: log_manager_app_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DATABASE_HOST"] %>
    database: postgres
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    port: 5432
    sslmode: verify-full
    sslrootcert: <%= Rails.root.join("tmp", "supabase-cert.crt").to_s %>
  cable:
    <<: *primary_production
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
