default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: log_manager_app_development

test:
  <<: *default
  database: log_manager_app_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DATABASE_HOST"] %>
    database: postgres
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    port: 5432
    prepared_statements: false
    sslmode: verify-full
    sslrootcert: <%= ENV["SUPABASE_SSL_CERT_PATH"] %>
  cache:
    <<: *primary_production
    database: log_manager_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: log_manager_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: log_manager_app_production_cable
    migrations_paths: db/cable_migrate
