default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: log_manager_app_development

test:
  <<: *default
  database: log_manager_app_test

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: postgres
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: 6543
